# Generated by Django 5.1.1 on 2024-10-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StuData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField(max_length=5)),
                ('stu_class', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
