# Generated by Django 5.1.1 on 2024-10-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studata',
            name='gender',
            field=models.TextField(choices=[('male', 'male'), ('female', 'female')]),
        ),
    ]
