# Generated by Django 5.1.1 on 2024-10-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_studata_roll_no_alter_studata_stu_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studata',
            name='date_of_entry',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
