# Generated by Django 5.1.1 on 2024-10-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_studata_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studata',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
