# Generated by Django 5.1.1 on 2024-10-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_studata_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studata',
            name='date_of_entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
