# Generated by Django 5.1.1 on 2024-10-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_studata_date_of_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studata',
            name='roll_no',
            field=models.SmallIntegerField(),
        ),
    ]
